DATE : 14/01/2026

### What is NumPy?

NumPy is a Python library used for working with arrays.  
It also has functions for working in domain of linear algebra, fourier transform, and matrices.  
NumPy was created in 2005 by Travis Oliphant. It is an open source project and you can use it freely.  
NumPy stands for Numerical Python.

#### Why Use NumPy?

In Python we have lists that serve the purpose of arrays, but they are slow to process.  
NumPy aims to provide an array object that is up to 50x faster than traditional Python lists.  
The array object in NumPy is called ndarray, it provides a lot of supporting functions that make working with ndarray very easy.  
Arrays are very frequently used in data science, where speed and resources are very important.

| Feature                     | **NumPy Array**                            | **Python List (Array List)**                  |
| --------------------------- | ------------------------------------------ | --------------------------------------------- |
| **Library**                 | Comes from **NumPy library**               | Built-in in Python                            |
| **Data type**               | Stores **same type** of data (homogeneous) | Can store **different types** (heterogeneous) |
| **Speed**                   | Very **fast** for calculations             | **Slower** for math operations                |
| **Memory usage**            | Uses **less memory**                       | Uses **more memory**                          |
| **Mathematical operations** | Supports **direct math operations**        | Needs loops for math                          |
| **Dimensions**              | Supports **1D, 2D, 3D, n-D arrays**        | Mostly **1D**, nested lists for 2D            |
| **Performance**             | Optimized for **large data**               | Not optimized for large data                  |
| **Used for**                | Scientific computing, ML, Data Science     | General purpose programming                   |
| **Functions**               | Many built-in math & statistical functions | Limited math functions                        |
| **Example use**             | Matrix, vectors, numerical analysis        | Storing mixed data                            |


##### Why is NumPy Faster Than Lists?

NumPy arrays are stored at one continuous place in memory unlike lists, so processes can access and manipulate them very efficiently.  
This behavior is called locality of reference in computer science.  
This is the main reason why NumPy is faster than lists. Also it is optimized to work with latest CPU architectures.

Installation of numpy :  pip install numpy

In [1]:
# numpy example

import numpy as np

a=np.array([1, 2, 3])
print(a)

[1 2 3]


In [2]:
import numpy as np

print(np.__version__)

2.4.1


#### Create a NumPy ndarray Object  

NumPy is used to work with arrays. The array object in NumPy is called ndarray.  
We can create a NumPy ndarray object by using the array() function.

In [3]:
import numpy as np

x= np.array([10,20,30,40,50])
print(x)
print(type(x))

[10 20 30 40 50]
<class 'numpy.ndarray'>


DATE : 15/01/2026

type(): This built-in Python function tells us the type of the object passed to it. Like in above code it shows that arr is numpy.ndarray type.

To create an ndarray, we can pass a list, tuple or any array-like object into the array() method, and it will be converted into an ndarray:

In [4]:
# Use a tuple to create a NumPy array:

import numpy as np

a= np.array((1,2,3,4,5))
print(a)
print(type(a))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [5]:
# 0-dimensional array

import numpy as np
a=np.array(12)
print(a)

12


In [6]:
# 1-dimensional array

# [1,2,3] = 1-dimensional array

import numpy as np
p=np.array([12,10,2005])
print(p)

[  12   10 2005]


In [7]:
# 2-dimensional array

''' 
[   
    [1,2,3]
    [10,20,30] 
]
'''

import numpy as np
q=np.array([[1,2,3,4,5],[10,20,30,40,50]])
print(q)

[[ 1  2  3  4  5]
 [10 20 30 40 50]]


In [8]:
# 3-dimensional array

'''
[ 
    [ [1,2,3],[4,5,6] ]
    [ [7,8,9],[10,11,12] ]
]
'''

import numpy as np
r=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(r)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [9]:
# checking dimensions of an array

'''NumPy Arrays provides the ndim attribute that returns an integer that tells us 
how many dimensions the array have.
'''

print(a.ndim)
print(p.ndim)
print(q.ndim)
print(r.ndim)

0
1
2
3


In [10]:
# by default declaring array dimensions

'''Higher Dimensional Arrays
An array can have any number of dimensions.
When the array is created, you can define the number of dimensions by using the ndmin argument.
'''

import numpy as np
s=np.array([1,2,3,4,5],ndmin=5)
print(s)
print('number of dimensions :',s.ndim)

[[[[[1 2 3 4 5]]]]]
number of dimensions : 5


In [11]:
# array indexing of 0 dimensional array

'''
    array indexing starts from 0
'''

import numpy as n

t=n.array([1,2,3,4,5])
print(t[0])
print(t[4])
print(t[-4])

1
5
2


In [12]:
# array indexing of 2 dimensional array

import numpy as np
a=np.array([[1,2,3],[10,20,30]])
print(a)
print("elements at 0th row and 0th column:",a[0,0])
print("elements at 1th row and 0th column:",a[1,0])
print("elements at 0th row and 1th column:",a[0,1])
print("elements at 1th row and 1th column:",a[1,1])
print("elements at 0th row and 2th column:",a[0,2])
print("elements at 1th row and 2th column:",a[1,2])

[[ 1  2  3]
 [10 20 30]]
elements at 0th row and 0th column: 1
elements at 1th row and 0th column: 10
elements at 0th row and 1th column: 2
elements at 1th row and 1th column: 20
elements at 0th row and 2th column: 3
elements at 1th row and 2th column: 30


In [13]:
# array indexing of 3 dimensional array

import numpy as np
p=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(p)
print("elements at 0th row ,0th column and 0th depth:",p[0,0,0])
print("elements at 0th row ,0th column and 1th depth:",p[0,0,1])
print("elements at 0th row ,0th column and 2th depth:",p[0,0,2])
print("elements at 1th row ,0th column and 0th depth:",p [1,0,0])
print("elements at 1th row ,0th column and 1th depth:",p [1,0,1])
print("elements at 1th row ,0th column and 2th depth:",p [1,0,2])
print("elements at 0th row ,1th column and 0th depth:",p [0,1,0])
print("elements at 0th row ,1th column and 1th depth:",p [0,1,1])
print("elements at 0th row ,1th column and 2th depth:",p [0,1,2])
print("elements at 1th row ,1th column and 0th depth:",p [1,1,0])
print("elements at 1th row ,1th column and 1th depth:",p [1,1,1])
print("elements at 1th row ,1th column and 2th depth:",p [1,1,2])

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
elements at 0th row ,0th column and 0th depth: 1
elements at 0th row ,0th column and 1th depth: 2
elements at 0th row ,0th column and 2th depth: 3
elements at 1th row ,0th column and 0th depth: 7
elements at 1th row ,0th column and 1th depth: 8
elements at 1th row ,0th column and 2th depth: 9
elements at 0th row ,1th column and 0th depth: 4
elements at 0th row ,1th column and 1th depth: 5
elements at 0th row ,1th column and 2th depth: 6
elements at 1th row ,1th column and 0th depth: 10
elements at 1th row ,1th column and 1th depth: 11
elements at 1th row ,1th column and 2th depth: 12


DATE : 16/01/2026

In [14]:
import numpy as np

a=np.array([1.2,"Vaishu"])      # numpy allow same data type here integer convert into string
print(a)

['1.2' 'Vaishu']


In [15]:
# arange like range()

import numpy as np

a= np.arange(1,10)      # start,stop,step
b=np.arange(1,12,3)
print(a)
print(b)

[1 2 3 4 5 6 7 8 9]
[ 1  4  7 10]


In [16]:
# linspace= prints value between start value to end

a=np.linspace(0,1,5)    # values between evenly space into 5
b=np.linspace(1,100,10)
print(a)
print(b)

[0.   0.25 0.5  0.75 1.  ]
[  1.  12.  23.  34.  45.  56.  67.  78.  89. 100.]


In [17]:
# logspace=lograthmic scale array

# np.logspace(start,ending -> powers, number of values for evenly spacing)
arr=np.logspace(1,3,3)  # 10^1 -> 10^3....3 points
print(arr)

[  10.  100. 1000.]


In [18]:
# zeros = array full of zeros

import numpy as np
x=np.zeros(5) # how many zero want in array
print(x)


# using specific parameter (for matrix)

p=np.zeros([2,3])       # 2 rows 3 columns
print(p)

[0. 0. 0. 0. 0.]
[[0. 0. 0.]
 [0. 0. 0.]]


In [19]:
# ones= value one in array

arr=np.ones([2,3])      # by default it will be float
arr1=np.ones([4,2],dtype=int) 
print(arr)
print(arr1)

[[1. 1. 1.]
 [1. 1. 1.]]
[[1 1]
 [1 1]
 [1 1]
 [1 1]]


In [20]:
# full = create an array full of any value

arr=np.full(10,2)       # (times,no)
print(arr)

# 2d array

a=np.full([2,4],7)  #[row,column],default value
print(a)

[2 2 2 2 2 2 2 2 2 2]
[[7 7 7 7]
 [7 7 7 7]]


In [21]:
# empty = uninitialized array

a=np.empty([2,3])
print(a)

[[1. 1. 1.]
 [1. 1. 1.]]


In [22]:
# random.rand= random values between 0 and 1

# rand= for multidimensional array
# randn= normal distribution
# randint= random integers


arr=np.random.rand(10)
print(arr)
print("=============================================")

# for matrix
arr=np.random.rand(3,4)   # 3 rows 4 columns
print(arr)
print("=============================================")

p= np.random.randn(5)   # normal distribution mean=0, std=1
print(p)
print("=============================================")

q= np.random.randn(2,3)   # 2 rows 3 columns
print(q)
print("=============================================")

arr= np.random.randint(10,100)   # single random integer between 1 to 10  (start,stop,size=(2,3))  size for matrix (optional)
print(arr)
print("=============================================")

arr= np.random.randint(10,100,size=(2,3))   # matrix 2 rows 3 columns
print(arr)
print("=============================================")

[0.54741046 0.49345637 0.94262596 0.21742985 0.6702138  0.27221427
 0.66769134 0.53944665 0.29157255 0.47293843]
[[2.70310963e-01 2.08879945e-01 7.15833997e-01 5.07991106e-01]
 [7.23344423e-01 2.76562718e-02 3.63519974e-01 8.72761784e-05]
 [9.49565449e-01 6.98624569e-01 9.24045343e-01 5.34568781e-01]]
[-0.56947856 -0.8857769  -0.9319236  -0.07952013 -0.31095767]
[[ 1.13823464 -0.39618617  1.73731279]
 [-0.13733144 -0.80105835 -0.26092831]]
91
[[83 12 81]
 [10 43 78]]


DATE : 17/01/26

### NUMPY DATAYPES

| **Data Type**                             | **Description**                     | **Example**                                    |
| ----------------------------------------- | ----------------------------------- | ---------------------------------------------- |
| `int` (`int8`, `int16`, `int32`, `int64`) | Stores **whole numbers**            | `np.array([1, 2, 3], dtype=int)`               |
| `float` (`float16`, `float32`, `float64`) | Stores **decimal numbers**          | `np.array([1.2, 3.5, 6.8], dtype=float)`       |
| `complex` (`complex64`, `complex128`)     | Stores **real + imaginary numbers** | `np.array([1+2j, 3+4j])`                       |
| `bool`                                    | Stores **True / False** values      | `np.array([True, False, True])`                |
| `str_`                                    | Stores **text / characters**        | `np.array(["A", "B", "C"])`                    |
| `object`                                  | Stores **mixed data types**         | `np.array([1, "Hello", 2.5], dtype=object)`    |
| `datetime64`                              | Stores **date & time**              | `np.array(['2026-01-20'], dtype='datetime64')` |
| `timedelta64`                             | Stores **time difference**          | `np.array([5], dtype='timedelta64[D]')`        |


In [23]:
# data types in numpy

arr=np.array([1,2,3,4,5])
print(arr)
print(arr.dtype)

arr=np.array([1.5,2.5,3.5],dtype=str)
print(arr)
print(arr.dtype)

[1 2 3 4 5]
int64
['1.5' '2.5' '3.5']
<U3


In [24]:
### Type casting

'''
converts data type into another data type
by using astype
'''

arr=np.array([1,2,3,4,5])
print(arr)
print(arr.dtype)

new_arr=arr.astype(float)
print(new_arr)
print(new_arr.dtype)

new_arr2=arr.astype(int)
print(new_arr2)
print(new_arr2.dtype)

[1 2 3 4 5]
int64
[1. 2. 3. 4. 5.]
float64
[1 2 3 4 5]
int64


In [25]:
# type casting errors :

arr=np.array(["1","2","hello"])
new_arr=arr.astype(int)     # we cannot convert string into int and float
print(new_arr)

ValueError: invalid literal for int() with base 10: np.str_('hello')

In [ ]:
# attributes of numpy array

import numpy as np
arr=np.array([[1,2,3,4,5],[10,20,30,40,50]])
print(arr)
print(arr.ndim)    # no of dimensions
print(arr.shape)   # (rows,columns)
print(arr.size)    # total no of elements in array
print(arr.dtype)   # data type of array elements
print(arr.itemsize)  # size of each element in bytes

[[ 1  2  3  4  5]
 [10 20 30 40 50]]
2
(2, 5)
10
int64
8


In [ ]:
# reshaping of numpy array

'''
Reshaping means changing the shape of an array.
The shape of an array is the number of elements in each dimension.
'''

import numpy as np
arr=np.array([1,2,3,4,5,6])
print("original array:",arr)
reshaped_arr=arr.reshape(2,3)
print("reshaped array:",reshaped_arr)
reshaped_arr1=arr.reshape(3,2)
print("reshaped array:",reshaped_arr1)

original array: [1 2 3 4 5 6]
reshaped array: [[1 2 3]
 [4 5 6]]
reshaped array: [[1 2]
 [3 4]
 [5 6]]


In [ ]:
# ravel = converts multidimensional array into 1d array

ravel=reshaped_arr.ravel()
print("ravel array:",ravel)

ravel[0]=100
print("modified ravel array:",ravel)
print("original reshaped array after modifying ravel array:",reshaped_arr)

ravel array: [1 2 3 4 5 6]
modified ravel array: [100   2   3   4   5   6]
original reshaped array after modifying ravel array: [[100   2   3]
 [  4   5   6]]


In [ ]:
'''flatten = converts multidimensional array into 1d array 
but it returns a copy of original array whereas ravel returns reference of original array
'''

flatten=reshaped_arr.flatten()
print("flatten array:",flatten)

flatten[0]=200
print("modified flatten array:",flatten)
print("original reshaped array after modifying flatten array:",reshaped_arr)

flatten array: [100   2   3   4   5   6]
modified flatten array: [200   2   3   4   5   6]
original reshaped array after modifying flatten array: [[100   2   3]
 [  4   5   6]]


In [ ]:
# arithmetic Operations on array

import numpy as np
a=np.array([1,2,3])
b=np.array([4,5,6])

# addition
print(a+b)

# subtraction
print(a-b)
print(b-a) 

# division
print(b/a)
print(b//a)     # gives integer division

# multiplication
print(a*b)

# modulus(remainder)
print(b%a)

# exponent(power)
print(a**2)

[5 7 9]
[-3 -3 -3]
[3 3 3]
[4.  2.5 2. ]
[4 2 2]
[ 4 10 18]
[0 1 0]
[1 4 9]


DATE : 19/01/2026

In [ ]:
# Universal Function = ufuncs (inbuilt)

arr=np.array([1,4,9,16])

# square root = np.sqrt()
print(np.sqrt(arr))

# exponentioal = np.exp -> e^x -> x is any integer
print(np.exp([1,2]))

# sine function -> np.sin
angles=np.array([0,np.pi,np.pi/2])
print(np.sin(angles))

[1. 2. 3. 4.]
[2.71828183 7.3890561 ]
[0.0000000e+00 1.2246468e-16 1.0000000e+00]


In [ ]:
# indexing and slicing

arr=np.array([10,20,30,40,50])

# indexes
print(arr[0:3])         # indexing start from 0
print(arr[4])
print("======================================")

print(arr[0:3])         # here by default step will be 1
print(arr[0:3:2])       # [start:end (-1):step(-1)]
print(arr[1:4:2])
print("======================================")

# Negative indexing
print(arr[-1])
print(arr[-1:-5])   # step not mentioned
print(arr[-1:-5:-1])
print(arr[-1:-6:-1])
print(arr[-1:-4:-2])
print("======================================")

[10 20 30]
50
[10 20 30]
[10 30]
[20 40]
50
[]
[50 40 30 20]
[50 40 30 20 10]
[50 30]


In [ ]:
# multidimensional slicing

matrix=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(matrix)
print("-------------------------------------")
print(matrix[0:2])  # [stat,end(-1),row]
print("-------------------------------------")
print(matrix[0:2, 1:3])     # array[row_start:row_end , col_start:col_end]
print("-------------------------------------")
print(matrix[1: ,1:])
print("-------------------------------------")

[[1 2 3]
 [4 5 6]
 [7 8 9]]
-------------------------------------
[[1 2 3]
 [4 5 6]]
-------------------------------------
[[2 3]
 [5 6]]
-------------------------------------
[[5 6]
 [8 9]]
-------------------------------------


In [ ]:
# np.take -> built in function to perform indexing and slicing

arr=np.array([10,20,30,40,50])
ind=[0,2]
print(np.take(arr,ind))

[10 30]


In [ ]:
# Iterating with nditer()

arr=np.array([[1,2],[3,4]])
for x in np.nditer(arr):
    print(x,end=" ")

1 2 3 4 

In [ ]:
# ndenumerate() -> both index + value

for ind,x in np.ndenumerate(arr):
    print(ind,x)

(0, 0) 1
(0, 1) 2
(1, 0) 3
(1, 1) 4


In [ ]:
arr=np.array([1,2,3,4,5])
print("Original array:",arr)

# Views vs Copies

view=arr[1:3]
print("View array [1:3]:",view)

# index value changed
view[0]=200
print("After adding 200 at index 0:",view)

print("Original array:",arr)        # it affects to original data

# copy
copy=arr[1:3].copy()
print("Copy array [1:3]:",copy)

# index value changed
copy[0]=2
print("After adding 2 at index 0:",copy)

print("Original array:",arr)    # it doesnot affects on original data

Original array: [1 2 3 4 5]
View array [1:3]: [2 3]
After adding 200 at index 0: [200   3]
Original array: [  1 200   3   4   5]
Copy array [1:3]: [200   3]
After adding 2 at index 0: [2 3]
Original array: [  1 200   3   4   5]


In [ ]:
# array transpose

arr=np.array([[1,2],[3,4]])
print("Original Array:",arr)
print("Transpose Array:",arr.transpose())

Original Array: [[1 2]
 [3 4]]
Transpose Array: [[1 3]
 [2 4]]


In [ ]:
# Swapaxex -> swap 2 specific axes in a matrix

arr=np.array([[[1,2],[3,4]]])
print(arr.shape)
print(arr)

swap=np.swapaxes(arr,0,1)       # only axex swap
print(swap.shape)
print(arr)

(1, 2, 2)
[[[1 2]
  [3 4]]]
(2, 1, 2)
[[[1 2]
  [3 4]]]


In [ ]:
# array concatenation

a=np.array([1,2])
b=np.array([3,4])

combine = np.concatenate((a,b))
print(combine)

[1 2 3 4]


In [ ]:
arr1=np.array([[1,2],[3,4]])
arr2=np.array([[5,6],[7,8]])

# vstack
print(np.vstack((arr1,arr2)))

# hstack

print(np.hstack((arr1,arr2)))
print("----------------------------")

''' 
axis 0 -> array row wise
axis 1 -> array column wise
'''

print(np.stack((arr1,arr2),axis=0))
print(np.stack((arr1,arr2),axis=1))

[[1 2]
 [3 4]
 [5 6]
 [7 8]]
[[1 2 5 6]
 [3 4 7 8]]
----------------------------
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
[[[1 2]
  [5 6]]

 [[3 4]
  [7 8]]]


DATE : 19/01/2026

In [ ]:
# Splitting Arrays:

arr1 =np.array([[1,2],[3,4],[5,6],[7,8]])
print(arr1)

print(np.split(arr1,2))         # array split into 2 parts

print(np.hsplit(arr1,2))
print(np.vsplit(arr1,2))

[[1 2]
 [3 4]
 [5 6]
 [7 8]]
[array([[1, 2],
       [3, 4]]), array([[5, 6],
       [7, 8]])]
[array([[1],
       [3],
       [5],
       [7]]), array([[2],
       [4],
       [6],
       [8]])]
[array([[1, 2],
       [3, 4]]), array([[5, 6],
       [7, 8]])]


In [ ]:
#Repeating

arr=np.array([1,2,3])
print(arr)
print(np.repeat(arr,3))

#  tile -> repeate whole array

print(np.tile(arr,2))

[1 2 3]
[1 1 1 2 2 2 3 3 3]
[1 2 3 1 2 3]


In [ ]:
# Aggregate Functions

arr=np.array([1,2,3])

print(np.sum(arr))
print(np.mean(arr))
print(np.median(arr))
print(np.std(arr))
print(np.var(arr))
print(np.min(arr))
print(np.max(arr))

6
2.0
2.0
0.816496580927726
0.6666666666666666
1
3


In [ ]:
print(matrix)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [ ]:
print(np.sum(matrix,axis=1))        # row-wise
print(np.sum(matrix,axis=0))        # column-wise

[ 6 15 24]
[12 15 18]


In [ ]:
# cumuulative operations -> running total

print(arr)

[1 2 3]


In [ ]:
print(np.cumsum(arr))

[1 3 6]


In [ ]:
print(np.cumprod(arr))

[1 2 6]


In [ ]:
# conditional based choices

print(arr)

# where
result=np.where(arr<2,"low","high")
print(result)

# argwhere
arr=np.array([10,25,35,50])
print(np.argwhere(arr>20))      # index tells greater than 20

# logical
mask=np.logical_and(arr>15,arr<35)      # both condition should be true
print(mask)

[10 25 35 50]
['high' 'high' 'high' 'high']
[[1]
 [2]
 [3]]
[False  True False False]


In [ ]:
matrix

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
print(np.argwhere(matrix>5))

[[1 2]
 [2 0]
 [2 1]
 [2 2]]


In [ ]:
arr=np.array([100,2,3,4,5,6])
print(arr)

[100   2   3   4   5   6]


In [ ]:
#  logical and

mask=np.logical_and(arr>3,arr<6)
print(mask)
print(arr[mask])

[False False False  True  True False]
[4 5]


In [ ]:
# logical or

mask=np.logical_or(arr<4,arr>5)
print(mask)
print(arr[mask])

[ True  True  True False False  True]
[100   2   3   6]


### 📌 Broadcasting Rules in NumPy

Broadcasting in NumPy means performing operations on arrays of different shapes without explicitly reshaping them.

✅ Basic Broadcasting Rules

NumPy follows 3 main rules to check whether two arrays can be broadcast together:

🔹 Rule 1: Compare shapes from right to left

NumPy compares array shapes starting from the last dimension.  
Dimensions are checked one by one from right side.

🔹 Rule 2: Dimensions are compatible if

Two dimensions are compatible when:  
They are equal, OR  
One of them is 1  
If neither condition is true → ❌ Error

🔹 Rule 3: Missing dimensions are treated as size 1  

If one array has fewer dimensions, NumPy assumes missing dimensions = 1.

In [ ]:
# Broadcasting

image = np.array([[200,150],[100,250]])
print(image)
print(image.shape)

[[200 150]
 [100 250]]
(2, 2)


In [ ]:
brightness = image+50
print(brightness)

[[250 200]
 [150 300]]


In [ ]:
# Vectorization

# np.vectorize() -> convert a regular function to be applied on an array.

def square(x):
    return x*x

vfunc = np.vectorize(square)

In [ ]:
arr

array([100,   2,   3,   4,   5,   6])

In [ ]:
print(vfunc(arr))

[10000     4     9    16    25    36]


In [ ]:
# dealing with missing values

# np.nan -> not a number

a=np.array([1,2,np.nan,4])
print(a)

''''
np.inf and -np.inf -> positive and negative infinites
np.isnan
np.isinf
np.isfinite
these are the functions used to detect any null values, infinite value and finite value
'''

print(np.isnan(a))
b=np.array([1,np.nan,np.inf,10.2,40])
print(np.isinf(b))

new_b= np.nan_to_num(b)         # remove Nan/ infinite values.
print(new_b)


[ 1.  2. nan  4.]
[False False  True False]
[False False  True False False]
[1.00000000e+000 0.00000000e+000 1.79769313e+308 1.02000000e+001
 4.00000000e+001]
